language: python
python:
  - "2.7"
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=sqla9
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=lint
  - TOXENV=coverage
  - TOXENV=postgresql
install:
  - "pip install tox"
# command to run tests
script: tox
branches:
  only:
    - master
notifications:
  email: false