language: python
python:
  - "2.7"
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=sqla9
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=lint
  #- TOXENV=coverage
  - TOXENV=postgresql POSTGRESQL_URL=postgres://postgres:@localhost:5432/travis_ci_test
install:
  - "pip install tox"
# command to run tests
script: tox
services: postgresql
addons:
  postgresql: "9.3"
before_script:
  - sh -c "if [ -n '$POSTGRESQL_URL' ]; then psql -c 'create database travis_ci_test;' -U postgres; fi"
branches:
  only:
    - master
notifications:
  email: false